server:
  port: 18081

spring:
  application:
    name: auth-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/auth_service?serverTimezone=UTC&characterEncoding=UTF-8
    username: anan
    password: qwe123!!

logging:
  level:
    root: info
    io.ananworld.postservice: debug

jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
  expiration: 3600