server:
  port: 18082

spring:
  application:
    name: post-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/post_service?serverTimezone=UTC&characterEncoding=UTF-8
    username: anan
    password: qwe123!!

logging:
  level:
    root: info
    io.ananworld.postservice: debug
