server:
  port: 18080

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:18090/eureka

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:

        - id: member-service
          uri: http://localhost:18081/
          predicates:
            - Path=/api/user/**
          filters:
            - RemoveRequestHeader= Set-Cookie
            - RewritePath=/api/user/(?<path>.*), /$\{path}

        - id: post-service
          uri: http://localhost:18082/
          predicates:
            - Path=/api/post/**
          filters:
            - RemoveRequestHeader= Set-Cookie
            - RewritePath=/api/post/(?<path>.*), /$\{path}

      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - http://localhost:3001
            allowed-methods:
              - POST
              - GET
              - PUT
              - OPTIONS
              - DELETE
            allowed-headers:
              - Content-Type
              - Cookie
              - Access-Control-Allow-Headers
              - Authorization
              - X-Requested-With
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
            allow-credentials: true
#        add-to-simple-url-handler-mapping: true


#        corsConfigurations:
#          '[/**]':
#            allowedOrigins:
#
#            allow-credentials: true
#            allowedHeaders:
#              - x-requested-with
#              - authorization
#              - content-type
#              - credential
#              - X-AUTH-TOKEN
#              - X-CSRF-TOKEN
#            allowedMethods:
#              - POST
#              - GET
#              - PUT
#              - OPTIONS
#              - DELETE

jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY

